apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 522814728660.dkr.ecr.ap-south-1.amazonaws.com/expense-backend:v1
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: dev-backend
          - secretRef:
              name: dev-backend
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
              