apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-mysql
spec:
  selector:
    matchLabels:
      app: expense-mysql
  serviceName: "dev-mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: expense-mysql
    spec:
      containers:
      - name: dev-mysql
        image: 522814728660.dkr.ecr.ap-south-1.amazonaws.com/expense-mysql:v1
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: dev-mysql
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-mysql
                key: MYSQL_ROOT_PASSWORD
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 30  # Allow full startup
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          exec:
            command: ["mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
          initialDelaySeconds: 30  # Start checking sooner
          periodSeconds: 5        # More frequent checks
          failureThreshold: 1
  volumeClaimTemplates:
  - metadata:
      name: dev-mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense"
      resources:
        requests:
          storage: 1Gi