apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-mysql
spec:
  selector:
    matchLabels:
      app: expense-mysql
  serviceName: "dev-mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: expense-mysql
    spec:
      containers:
      - name: dev-mysql
        image: 522814728660.dkr.ecr.ap-south-1.amazonaws.com/expense-mysql:v1
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: dev-mysql
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-mysql
                key: MYSQL_ROOT_PASSWORD
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD -h 127.0.0.1"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: dev-mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense"
      resources:
        requests:
          storage: 1Gi